baseURL = 'https://bitcoin-safe.org/'
languageCode = 'en-Us'
title= 'Bitcoin Safe - A bitcoin savings wallet for the entire family'


timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


theme = "hugo-bootstrap-theme"

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[params]
  shorttitle= 'Bitcoin Safe'
  keywords = [
  "multisig",
  "siging device",
  "hardware wallet",
  "multiparty multisig collaboration",
  "remote signing",
  "secure chat",
  "PSBT sharing",
  "bitcoin security software",
  "best bitcoin multisig wallets",
  "bitcoin desktop wallet comparison",
  "open source bitcoin security tools",
  "what is multisig in bitcoin",
  "bitcoin wallet management software",
  "top bitcoin storage options",
  "collaborative bitcoin wallet solutions",
  "how to secure bitcoin for nonprofits",
  "bitcoin storage practices for artists",
  "trusted bitcoin management software",
  "importance of multisig for bitcoin",
  "bitcoin wallets for family offices",
  "bitcoin fund management tools",
  "choosing a bitcoin multisig provider",
  "analyzing bitcoin security risks",
  "how to set up a bitcoin wallet",
  "bitcoin wallets for research grants",
  "how to safeguard bitcoin investments",
  "how to manage bitcoin safely",
  "bitcoin asset management for families",
  "bitcoin security for small businesses",
  "future of bitcoin wallet management",
  "bitcoin insurance trust management",
  "secure bitcoin holding solutions",
  "bitcoin safekeeping methods",
  "how to use bitcoin multisig",
  "what is bitcoin key management",
  "bitcoin wallet security tips",
  "best practices for bitcoin security",
  "Bitcoin Safe",
  "Bitcoin Management Software",
  "Encrypted communication",
  "Private Key Storage",
  "Cold storage",
  "qr signing",
  "usb signing",
  "sd card signing",
  "Sneakernet",
  "Label synchonization",
  "Coin categories",
  "Airgapped Keys",
  "Comprehensive Reporting",
  "Detailed Analytics",
  "Multi-Device Compatibility",
  "Singlesig and Multisig Configurations",
  "Encrypted Remote Chat",
  "Nostr Protocol"
]


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
