[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "Download"
url = "download"
weight = 20
title = "Download"


[[main]]
identifier = "Features"
name = "üöÄFeatures"
url = "features"
weight = 50

[[main]]
identifier = "Knowledge"
name = "üè´Knowledge"
url = "knowledge"
weight = 55


[[main]]
identifier = "Donate"
name = "‚ö°Donate"
url = "donate"
weight = 60


[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/andreasgriffin/bitcoin-safe"
  weight = 10
  title = "Visit the GitHub project"


# [[social]]
#   name = "Email"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-email'><use href='images/feather/feather-sprite.svg#email'/></svg>"
#   url = "<a href='bitcoinsafe.strobe206@aleeas.com'>Example mailto link</a>"
#   weight = 10
#   title = "Mail me"


[[social]]
  name = "Nostr"
  pre = "<img src='/icons/nostr-logo-outline.svg' alt='Nostr' class='feather feather-github' />"
  url = "https://primal.net/p/npub1q67f4d7qdja237us384ryeekxsz88lz5kaawrcynwe4hqsnufr6s27up0e"
  weight = 20
  title = "Nostr Profile"



[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://x.com/BitcoinSafeOrg"
  weight = 21
  title = "Contact on Twitter"



[[social]]
  name = "Youtube"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-youtube'><use href='/images/feather/feather-sprite.svg#youtube'/></svg>"
  url = "https://www.youtube.com/@BitcoinSafeOrg"
  weight = 20
  title = "Channel on Youtube"
